spring.application.name=swedishpolls
spring.docker.compose.file=compose.dev.yaml
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/swedishpolls}
spring.datasource.username=${DATABASE_USER:swedishpolls}
spring.datasource.password=${DATABASE_PASSWORD}
spring.flyway.clean-disabled=true
spring.flyway.validate-on-migrate=true
polls.source-url=https://raw.githubusercontent.com/MansMeg/SwedishPolls/master/Data/Polls.csv
spring.http.serviceclient.poll-source.base-url=${polls.source-url}
spring.http.serviceclient.poll-source.connect-timeout=10s
spring.http.serviceclient.poll-source.read-timeout=30s
spring.http.serviceclient.poll-source.redirects=dont-follow
